name: Renovate
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@3064367f740a1a91cca218698a63902689cce200 # v46.1.20
        with:
          configurationFile: renovate-action.json5
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: ${{ vars.RENOVATE_LOG_LEVEL }}
          RENOVATE_GIT_AUTHOR: 'GudahttBot (Renovate) <gudahttbot+renovate@users.noreply.github.com>'
